"""
Gazebo simulation bringup for the strawberry tabletop AMR.

RUNS ON YOUR DEV ORIN, NOT THE PI RIG. Gazebo is a full 3D physics
simulator with GPU-accelerated rendering -- do not attempt this on either
Raspberry Pi. This is a desktop/Orin development and validation tool,
entirely separate from the field deployment launch files.

WHAT'S REUSED UNCHANGED FROM THE REAL ROBOT (this is the point of the
exercise -- validate the actual navigation/perception/mission code, not a
simulation-only reimplementation of it): row_navigation, safety_supervisor,
twist_mux, imu_filter_madgwick, robot_localization (EKF), slam_toolbox,
plant_perception, semantic_mapper, target_manager, coverage_planner,
mission_control, and (optionally) the full Nav2 stack -- every one of
these nodes is launched with the IDENTICAL package/executable/params used
in the field launch files. Only base_controller and the real sensor
drivers (rplidar_ros, astra_camera) are replaced -- by Gazebo's Ackermann
drive plugin and sensor plugins respectively, both defined in
robot_description/urdf/strawberry_amr_sim.urdf.xacro, both publishing on
the SAME topic names the real hardware nodes use. See that file's own
header comment for the full reasoning and its explicit honesty note about
what does and doesn't carry over faithfully (HSV perception tuning
specifically does not -- see GAZEBO_SIMULATION_GUIDE.md).

World selection: pick a world generated by
strawberry_amr_gazebo/scripts/generate_polytunnel_world.py -- 'lab'
(matches the shipped algorithm config exactly) or 'realistic' (wider,
commercial-scale estimate). See that script's own module docstring for the
full reasoning and honesty note on where the 'realistic' numbers come
from.
"""
import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription, GroupAction
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, Command
from launch.conditions import IfCondition, UnlessCondition
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue


def generate_launch_description():
    gz_pkg = get_package_share_directory('strawberry_amr_gazebo')
    desc_pkg = get_package_share_directory('robot_description')
    bringup = get_package_share_directory('robot_bringup')
    sensors = get_package_share_directory('sensor_bringup')
    rownav = get_package_share_directory('row_navigation')
    coverage = get_package_share_directory('coverage_planner')
    mission = get_package_share_directory('mission_control')
    plant = get_package_share_directory('plant_perception')

    ekf = os.path.join(bringup, 'config', 'ekf.yaml')
    slam = os.path.join(bringup, 'config', 'slam_toolbox.yaml')
    mux = os.path.join(bringup, 'config', 'twist_mux.yaml')
    nav2_params = os.path.join(bringup, 'config', 'nav2_params.yaml')
    imu_cfg = os.path.join(sensors, 'config', 'imu_filter.yaml')
    rownav_cfg = os.path.join(rownav, 'config', 'row_navigation_params.yaml')
    coverage_cfg = os.path.join(coverage, 'config', 'coverage_params.yaml')
    mission_cfg = os.path.join(mission, 'config', 'mission_control_params.yaml')
    plant_cfg = os.path.join(plant, 'config', 'plant_detector_params.yaml')

    world = LaunchConfiguration('world')
    use_nav2 = LaunchConfiguration('use_nav2')
    use_camera_stack = LaunchConfiguration('use_camera_stack')
    mission_phase = LaunchConfiguration('mission_phase')
    exploration_mode = LaunchConfiguration('exploration_mode')

    sim_urdf = os.path.join(desc_pkg, 'urdf', 'strawberry_amr_sim.urdf.xacro')
    robot_description = ParameterValue(
        Command(['xacro ', sim_urdf]), value_type=str)

    nav2_lifecycle_nodes = ['controller_server', 'planner_server',
                            'behavior_server', 'bt_navigator']

    return LaunchDescription([
        DeclareLaunchArgument(
            'world', default_value=os.path.join(gz_pkg, 'worlds', 'irish_polytunnel_lab.world'),
            description="Full path to a world generated by generate_polytunnel_world.py. "
                        "Default is the 'lab' preset -- matches the shipped algorithm config."),
        DeclareLaunchArgument('use_nav2', default_value='true'),
        DeclareLaunchArgument('use_camera_stack', default_value='true'),
        DeclareLaunchArgument(
            'mission_phase', default_value='nav',
            description="'mapping' | 'nav' | 'explore' -- passed straight to "
                        "mission_control_node's phase parameter. Previously hardcoded to "
                        "'nav' here with no way to override at launch time, which meant "
                        "explore mode could not be exercised in simulation without hand-"
                        "editing this file."),
        DeclareLaunchArgument(
            'exploration_mode', default_value='false',
            description="Set true together with mission_phase:=explore to enable "
                        "row_navigation's reactive row-discovery (row_nav_node.py's own "
                        "exploration_mode parameter). Kept as a separate explicit argument "
                        "rather than derived from mission_phase, so this file never silently "
                        "guesses at row_navigation's flag on your behalf."),

        # ---- Gazebo server + client ----
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                os.path.join(get_package_share_directory('gazebo_ros'),
                             'launch', 'gazebo.launch.py')),
            launch_arguments={'world': world}.items()),

        # ---- robot_state_publisher (drives TF from the SIM urdf, which
        # includes the real urdf unmodified plus the Gazebo plugins) ----
        Node(package='robot_state_publisher', executable='robot_state_publisher',
             name='robot_state_publisher', output='screen',
             parameters=[{'robot_description': robot_description}]),

        # ---- spawn the robot at the entrance to row 0 ----
        Node(package='gazebo_ros', executable='spawn_entity.py',
             name='spawn_strawberry_amr', output='screen',
             arguments=['-topic', 'robot_description', '-entity', 'strawberry_amr',
                        '-x', '-0.5', '-y', '0.0', '-z', '0.05']),

        # ---- IMU filter: IDENTICAL node/config to the real robot; Gazebo's
        # IMU plugin publishes raw accel/gyro on /imu/data_raw same as
        # base_controller does on real hardware ----
        Node(package='imu_filter_madgwick', executable='imu_filter_madgwick_node',
             name='imu_filter_madgwick', output='screen', parameters=[imu_cfg]),

        # ---- state estimation, row-following, safety, arbitration:
        # IDENTICAL nodes/configs to the real robot ----
        Node(package='robot_localization', executable='ekf_node',
             name='ekf_filter_node', output='screen', parameters=[ekf]),
        # Two Node entries rather than one with a substituted boolean
        # parameter value: launch_ros's string-to-bool coercion for a
        # LaunchConfiguration substitution passed as a ROS parameter value
        # is not something that can be executed/verified in this dev
        # environment (no ROS 2 toolchain -- see CLAUDE.md), and getting it
        # wrong silently (e.g. Python's bool("false") is True) is exactly
        # the class of bug this project's own review discipline exists to
        # catch. IfCondition/UnlessCondition on the same launch argument is
        # the pattern already proven to work elsewhere in this file
        # (use_nav2, use_camera_stack) -- reused here rather than risking
        # an unverifiable new mechanism.
        Node(package='row_navigation', executable='row_nav_node',
             name='row_nav_node', output='screen', parameters=[rownav_cfg],
             condition=UnlessCondition(exploration_mode)),
        Node(package='row_navigation', executable='row_nav_node',
             name='row_nav_node', output='screen',
             parameters=[rownav_cfg, {'exploration_mode': True}],
             condition=IfCondition(exploration_mode)),
        Node(package='safety_supervisor', executable='safety_supervisor_node',
             name='safety_supervisor_node', output='screen'),
        Node(package='twist_mux', executable='twist_mux', name='twist_mux',
             output='screen', parameters=[mux],
             remappings=[('/cmd_vel_out', '/cmd_vel')]),

        # ---- SLAM: mapping mode by default, same config as Phase 1 field
        # deployment ----
        Node(package='slam_toolbox', executable='async_slam_toolbox_node',
             name='slam_toolbox', output='screen', parameters=[slam]),

        # ---- mission sequencing + Orin command interface: IDENTICAL to
        # the real robot ----
        Node(package='coverage_planner', executable='coverage_planner_node',
             name='coverage_planner_node', output='screen', parameters=[coverage_cfg]),
        # 'phase' is a string ROS parameter and mission_phase resolves to a
        # string -- no type-coercion risk here, unlike exploration_mode
        # above, so a direct substitution is safe.
        Node(package='mission_control', executable='mission_control_node',
             name='mission_control_node', output='screen',
             parameters=[mission_cfg, {'phase': mission_phase}]),

        # ---- perception + mapping (optional -- HSV tuning does not
        # transfer faithfully from Gazebo's rendering to the real camera,
        # see this file's module docstring; still useful as a functional
        # smoke test) ----
        GroupAction(condition=IfCondition(use_camera_stack), actions=[
            Node(package='plant_perception', executable='plant_detector_node',
                 name='plant_detector_node', output='screen',
                 parameters=[plant_cfg]),
            Node(package='semantic_mapper', executable='semantic_mapper_node',
                 name='semantic_mapper_node', output='screen'),
            Node(package='target_manager', executable='target_manager_node',
                 name='target_manager_node', output='screen'),
        ]),

        # ---- Nav2 (optional): IDENTICAL config to the real robot's Phase
        # 2 -- Smac Hybrid planner + car-safe Regulated Pure Pursuit ----
        GroupAction(condition=IfCondition(use_nav2), actions=[
            Node(package='nav2_controller', executable='controller_server',
                 name='controller_server', output='screen',
                 parameters=[nav2_params],
                 remappings=[('cmd_vel', 'cmd_vel_nav')]),
            Node(package='nav2_planner', executable='planner_server',
                 name='planner_server', output='screen', parameters=[nav2_params]),
            Node(package='nav2_behaviors', executable='behavior_server',
                 name='behavior_server', output='screen', parameters=[nav2_params]),
            Node(package='nav2_bt_navigator', executable='bt_navigator',
                 name='bt_navigator', output='screen', parameters=[nav2_params]),
            Node(package='nav2_lifecycle_manager', executable='lifecycle_manager',
                 name='lifecycle_manager_navigation', output='screen',
                 parameters=[{'autostart': True, 'node_names': nav2_lifecycle_nodes}]),
        ]),
    ])
